# Generated by Django 3.1 on 2020-09-03 13:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureSlotModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WritingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('short_title', models.CharField(max_length=100)),
                ('category', models.CharField(default='writing', max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('subgenre', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('publish_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('owner', models.CharField(max_length=50)),
                ('snippet', models.TextField()),
                ('content', models.TextField()),
                ('thumbnail', models.ImageField(default='media/tb.jpg', upload_to='media/')),
                ('tags', models.CharField(max_length=200)),
                ('feature_slot', models.OneToOneField(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='writing.featureslotmodel')),
            ],
        ),
    ]
