# Generated by Django 3.1 on 2020-09-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writingmodel',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
