# Generated by Django 3.1 on 2020-09-06 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0002_auto_20200906_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writingmodel',
            name='feature_slot',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
