# Generated by Django 3.1 on 2020-09-09 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0003_auto_20200906_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writingmodel',
            name='title',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
