# Generated by Django 3.1 on 2020-09-14 14:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('short_title', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('subgenre', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('publish_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('owner', models.CharField(max_length=50)),
                ('snippet', models.TextField(max_length=250)),
                ('content', models.TextField()),
                ('thumbnail', models.ImageField(default='default_thumbnail.jpg', upload_to='thumbnails/')),
                ('tags', models.CharField(max_length=200)),
                ('frontpage_feature_bool', models.BooleanField(default=False)),
                ('frontpage_feature_slot', models.IntegerField(blank=True, null=True, unique=True)),
                ('category_feature_bool', models.BooleanField(default=False)),
                ('category_feature_slot', models.IntegerField(blank=True, null=True, unique=True)),
                ('is_published', models.BooleanField(default=False)),
            ],
        ),
    ]
