# Generated by Django 3.1 on 2020-09-11 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalmodel',
            name='snippet',
            field=models.TextField(max_length=250),
        ),
    ]
