# Generated by Django 3.1 on 2020-09-10 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_models', '0002_auto_20200909_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalmodel',
            name='snippet',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='generalmodel',
            name='thumbnail',
            field=models.ImageField(default='default_thumbnail.jpg', upload_to='thumbnails/'),
        ),
    ]
